Handle F12 socket in InitTmuxSessions script
Sets up the F12 tmux socket with predefined sessions as well.
Since the script now handles multiple sockets, it got renamed
from InitF10Session to InitTmuxSessions.

diff --git a/Dotfiles/bin/InitTmuxSessions b/Dotfiles/bin/InitTmuxSessions
--- a/Dotfiles/bin/InitTmuxSessions
+++ b/Dotfiles/bin/InitTmuxSessions
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-# Name:          InitF10Session
-# Description:   Initializes the tmux's F10 socket with predefined sessions.
+# Name:          InitTmuxSessions
+# Description:   Initializes the common tmux's sockets (F10, F12) with predefined sessions.
 # Options:       -k|--kill-sessions:
 #                    Determines whether killing old sessions is allowed when trying to create a new session.
 #                    If set, old sessions will be killed if their name match new session's name.
@@ -31,6 +31,14 @@ function create_session() {
 
   tmux -L "${TARGET_SOCKET}" new-session -d -s "${1}"
 }
+
+# Prints error message and exits with code 100 if ${TARGET_SOCKET} is not a socket file.
+function ensure_target_socket_exists() {
+  if [ ! -S "${TMUX_TMPDIR}/tmux-1000/${TARGET_SOCKET}" ]; then
+    >&2 printf "Critical error: %s socket not found.\n" "${TARGET_SOCKET}"
+    exit 100
+  fi
+}
 ################################################################################
 
 while [ "${#}" -gt 0 ]; do
@@ -44,11 +52,7 @@ done
 
 
 TARGET_SOCKET=F10
-if [ ! -S "${TMUX_TMPDIR}/tmux-1000/${TARGET_SOCKET}" ]; then
-  >&2 printf "Critical error: %s socket not found.\n" "${TARGET_SOCKET}"
-  exit 100
-fi
-
+ensure_target_socket_exists
 # Creates a default session for own opensource/github projects:
 SESSION_OPENSOURCE="Opensource"
 AGRAL_DIR="${HOME}/Repos/agral"
@@ -63,5 +67,31 @@ cd "${DOTFILES_DIR}"
 create_session "${SESSION_DOTFILES}"
 # First window: The contents of Dotfiles repository:
 tmux -L "${TARGET_SOCKET}" rename-window -t "${SESSION_DOTFILES}:1" "Dotfiles"
+
+
+TARGET_SOCKET=F12
+ensure_target_socket_exists
+SESSION_MUSIC="Music"
+cd "${HOME}/Audio/Music/"
+create_session "${SESSION_MUSIC}"
+# First window: ncmpcpp controlling the main mpd instance:
+tmux -L "${TARGET_SOCKET}" rename-window -t "${SESSION_MUSIC}:1" "Music"
+tmux -L "${TARGET_SOCKET}" send-keys -t "${SESSION_MUSIC}:1" "ncmpcpp -c ${HOME}/.ncmpcpp/config" Enter
+
+# Second window: ncmpcpp controlling the podcasts mpd instance:
+tmux -L "${TARGET_SOCKET}" new-window -t "${SESSION_MUSIC}:2" -n "Podcasts"
+tmux -L "${TARGET_SOCKET}" send-keys -t "${SESSION_MUSIC}:2" "ncmpcpp -c ${HOME}/.ncmpcpp/podcast_config" Enter
+
+# Third window: ncmpcpp controlling the incoming mpd instance:
+tmux -L "${TARGET_SOCKET}" new-window -t "${SESSION_MUSIC}:3" -n "Incoming"
+tmux -L "${TARGET_SOCKET}" send-keys -t "${SESSION_MUSIC}:3" "ncmpcpp -c ${HOME}/.ncmpcpp/incoming_config" Enter
+
+# Fourth window: downloading the streamed content:
+cd "${HOME}/IN/music"
+tmux -L "${TARGET_SOCKET}" new-window -t "${SESSION_MUSIC}:4" -n "Ripping"
+
+# Focuses on the first window:
+tmux -L "${TARGET_SOCKET}" select-window -t "${SESSION_MUSIC}:1"
+
 
 printf "Successfully completed.\n"
